// Shared contract types for Sudoku platform

/**
 * Difficulty levels supported by the Sudoku platform.
 */
export enum Difficulty {
  Easy = "easy",
  Medium = "medium",
  Hard = "hard",
}

/**
 * A 9x9 Sudoku board where each cell is a number from 1‑9 or 0 for empty.
 * The type is a two‑dimensional array of numbers. Runtime validation should
 * ensure the correct dimensions; the type system only guarantees the shape.
 */
export type Board = number[][];

/**
 * Core domain entity representing a generated puzzle.
 */
export interface Puzzle {
  board: Board;
}

/**
 * Request payload for GET /puzzle (expressed as query parameters).
 */
export interface GetPuzzleRequest {
  difficulty: Difficulty;
}

/**
 * Response payload for GET /puzzle.
 */
export interface GetPuzzleResponse {
  board: Board;
}

/**
 * Request payload for POST /validate.
 */
export interface ValidatePuzzleRequest {
  board: Board;
}

/**
 * Response payload for POST /validate.
 */
export interface ValidatePuzzleResponse {
  correct: boolean;
}

/**
 * Core domain entity representing a stored score.
 */
export interface Score {
  /** Unique identifier generated by the Scores Service */
  id: string;
  playerName: string;
  difficulty: Difficulty;
  /** Time to solve in seconds */
  timeToSolve: number;
}

/**
 * Request payload for POST /scores.
 */
export interface PostScoreRequest {
  playerName: string;
  difficulty: Difficulty;
  timeToSolve: number;
}

/**
 * Response payload for POST /scores.
 */
export interface PostScoreResponse {
  id: string;
}

/**
 * Score entry returned in a leaderboard (does not include the internal id).
 */
export interface LeaderboardScore {
  playerName: string;
  difficulty: Difficulty;
  timeToSolve: number;
}

/**
 * Request payload for GET /leaderboard (expressed as query parameters).
 */
export interface GetLeaderboardRequest {
  difficulty: Difficulty;
}

/**
 * Response payload for GET /leaderboard.
 */
export interface GetLeaderboardResponse {
  scores: LeaderboardScore[];
}
