/**
 * Internal type definitions for the scores service.
 * These are used for database interactions and are separate from the shared contracts
 * to keep the service implementation decoupled from the API contract shapes.
 */

import type { Difficulty } from '@init-sudoku-post6/contracts';

/** Represents a stored score record. */
export interface Score {
  /** Primary key generated by SQLite. */
  id: number;
  /** Player's display name. */
  playerName: string;
  /** Difficulty of the puzzle solved. */
  difficulty: Difficulty;
  /** Time taken to solve the puzzle, in milliseconds. */
  timeTakenMs: number;
  /** ISO‑8601 timestamp when the score was recorded. */
  achievedAt: string;
}

/** Shape of a leaderboard entry returned to clients – matches the shared contract. */
export type LeaderboardEntry = {
  playerName: string;
  timeTakenMs: number;
  achievedAt: string;
};
